version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: nestjs-backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
